# Generated by Django 3.1.2 on 2021-04-12 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField(max_length=120)),
                ('made_on', models.DateTimeField(verbose_name='date published')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 4, 12, 23, 9, 21, 878713))),
            ],
        ),
    ]
