# Generated by Django 3.1.2 on 2021-04-12 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtweet',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 0, 41, 6, 74708)),
        ),
    ]
