# Generated by Django 3.1.2 on 2021-04-12 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20210413_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtweet',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 0, 45, 0, 886118)),
        ),
    ]
