# Generated by Django 3.1.2 on 2021-04-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20210413_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtweet',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newtweet',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
